variables:
  ENABLE_VMI: 0

stages:
  - coding-style
  - tidy
  - build
  - doc
  - proof

pages:
  stage: doc
  image: registry.gitlab.com/bedrocksystems/docker-image:doc
  script:
    - make doc
    - mv doc/html public
  artifacts:
    paths:
      - public
  only:
    - master

.prepare-common:
  image: registry.gitlab.com/bedrocksystems/docker-image:latest
  variables:
    ERR_ON_WARN: '1'
    VERBOSE: '1'
    LLVM_BASE_DIR: '/usr/lib/llvm/bin/'
  before_script:
    - cd ..
    - git clone https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.com/bedrocksystems/pico.git
    - mkdir -p pico/lib
    - cp -R vml pico/lib/
    - cd pico
    - make init BOARD=${BOARD} ENABLE_VMI=$ENABLE_VMI GITLAB_URL=https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.com/bedrocksystems/
  only:
    - merge_requests
    - pipelines

.prepare-aarch64:
  extends: .prepare-common
  variables:
    TARGET: 'aarch64'
    BOARD: 'qemu'
    PLATFORM: 'bedrock'

tidy-aarch64:
  extends: .prepare-aarch64
  stage: tidy
  variables:
    LLVM: '1'
    VML_PATH: '${CI_BUILDS_DIR}/bedrocksystems/pico/lib/vml/'
  script:
    - make -C $VML_PATH tidy -k
  allow_failure: true # For now, we don't strictly enforce the coding style

clang-format-check:
  stage: coding-style
  image: registry.gitlab.com/bedrocksystems/docker-image:coding-style
  script:
    - bash support/scripts/check_coding_style.sh
  only:
    - merge_requests
  allow_failure: true # For now, we don't strictly enforce the coding style

build-llvm-platform_posix:
  image: registry.gitlab.com/bedrocksystems/docker-image:vmm-platform-posix
  stage: build
  variables:
    CXX: 'clang++'
    ERR_ON_WARN: '1'
  script:
    - make
  only:
    - merge_requests
    - pipelines

proof-pico:
  stage: proof
  image: registry.gitlab.com/bedrocksystems/docker-image:cpp2v-llvm${LLVM_VER}
  variables:
    LLVM_VER: "10"
    DIRINPICO: lib/vml
  script:
    - git clone https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.com/bedrocksystems/pico.git /tmp/.pico
    - cd /tmp/.pico
    - ./incrproofci.sh
  artifacts:
    paths:
      - .pico
  only:
    - merge_requests
    - pipelines
