#
# Makefile
#
# Copyright (C) 2022 BedRock Systems, Inc.
# All rights reserved.
#
# This software is distributed under the terms of the BedRock Open-Source License.
# See the LICENSE-BedRock file in the repository root for details.
#

include $(BHV_ROOT)/support/build/rules.mk
