#
# Copyright (C) 2019-2023 BedRock Systems, Inc.
# All rights reserved.
#
# This software is distributed under the terms of the BedRock Open-Source License.
# See the LICENSE-BedRock file in the repository root for details.
#

LINKLIBS  = vbus timer gic cpu_model vcpu_roundup virtio_console virtio_net virtio_base simple_as arch_api posix_core
CC_SRCS = virtio_example.cpp
