#
# Copyright (C) 2019-2024 BlueRock Security, Inc.
# All rights reserved.
#
# This software is distributed under the terms of the BlueRock Open-Source License.
# See the LICENSE-BlueRock file in the repository root for details.
#

LINKLIBS  = vbus gic simple_as arch_api vpl011 msr timer cpu_model vcpu_roundup virtio_console virtio_net posix_core
LINKLIBS += vmm_debug
CC_SRCS = vbus_example.cpp
