#
# Makefile
#
# Copyright (C) 2020-2023 BlueRock Security, Inc.
# All rights reserved.
#
# This software is distributed under the terms of the BlueRock Open-Source License.
# See the LICENSE-BlueRock file in the repository root for details.
#

CC_SRCS = simple_as.cpp
