#
# Makefile
#
# Copyright (C) 2021-2023 BedRock Systems, Inc.
# All rights reserved.
#
# This software is distributed under the terms of the BedRock Open-Source License.
# See the LICENSE-BedRock file in the repository root for details.
#

CC_SRCS = virtio_sock.cpp
